/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.okr.service;
import cn.zhuatech.okr.common.BusinessException; import cn.zhuatech.okr.dto.OkrDto.*; import cn.zhuatech.okr.model.*; import cn.zhuatech.okr.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class OkrService {
    private final ObjectiveRepository orders; private final ProgressUpdateRepository reports; private final InitiativeRepository initiative; private final CheckInRepository checkIns; private final CurrentUserService current;
    public OkrService(ObjectiveRepository orders,ProgressUpdateRepository reports,InitiativeRepository initiative,CheckInRepository checkIns,CurrentUserService current){this.orders=orders;this.reports=reports;this.initiative=initiative;this.checkIns=checkIns;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getDepartmentCode();List<Objective> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByDepartmentCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<ObjectiveView> objectives(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){Objective order=orders.findById(id).orElseThrow(()->new BusinessException("目标任务不存在"));if(order.getStatus()==Objective.Status.COMPLETED)throw new BusinessException("已完成目标不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成权重不能超过目标剩余权重");order.report(request.goodQty(),request.defectQty());reports.save(new ProgressUpdate(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<Objective> list){int planned=list.stream().mapToInt(Objective::getPlannedQty).sum(),done=list.stream().mapToInt(Objective::getCompletedQty).sum(),defects=list.stream().mapToInt(Objective::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("目标权重",String.format("%,d",planned),list.size()+" 张目标任务","blue"),new Metric("目标完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("信心指数",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项风险","warn"),new Metric("目标风险",initiative.countByStatus(Initiative.Status.ALARM)+"",checkIns.countByResult(CheckIn.Result.PENDING)+" 项待更新","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),initiative.findAllByOrderByCodeAsc().stream().map(e->new InitiativeView(e.getCode(),e.getName(),e.getDepartment().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),checkIns.findTop10ByOrderByIdDesc().stream().map(i->new CheckInView(i.getCheckInNo(),i.getObjective().getOrderNo(),i.getObjective().getProductName(),i.getCheckInType(),i.getSampleQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private ObjectiveView view(Objective o){return new ObjectiveView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getDepartment().getName(),o.getDepartment().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(Objective o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
